name: Examples

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r examples/sentiment_analysis/requirements.txt
          pip install -r examples/image_classifier/requirements.txt
      - name: Sentiment analysis
        run: |
          model_test generate "examples/sentiment_analysis/"
          model_test run "examples/sentiment_analysis/"
      - name: Image classifier
        run: |
          model_test generate "examples/image_classifier/"
          model_test run "examples/image_classifier/"
